sudo: require
dist: bionic
language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - sudo apt-get install latexmk

script:
  - make clean
  - make -B

