# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    name: Build Docker image for LaTeX
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bin/Dockerfile
          push: true
          tags: mathematicalmichael/latex:thesis
          build-args: |
            USER_ID=1000
            GROUP_ID=1000

      - name: Image digest
        run: echo ${{ steps.push_to_dockerhub.outputs.digest }}

  build_python:
    name: Build Docker image for Python (Fenics)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bin/Dockerfile-fenics
          push: true
          tags: mathematicalmichael/python:thesis
          build-args: |
            USER_ID=1000
            GROUP_ID=1000

      - name: Image digest
        run: echo ${{ steps.push_to_dockerhub.outputs.digest }}

