name: Validate Examples

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: 
      - master
  schedule:
      - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Use docker to handle dependencies and prepend executables to PATH
    - name: Pull + retag docker image for Python (3.6) dependencies (quay.io/fenics)
      run: |
        docker pull mathematicalmichael/python:thesis
        docker tag mathematicalmichael/python:thesis python:thesis

    - name: Set up PATH for binaries
      run: echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV

    - name: Generate examples with python
      run: |
        cd examples
        make clean
        make
