name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'
  schedule:
      - cron: "0 0 */7 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull + retag docker images for LaTeX dependencies
      run: |        
        docker pull mathematicalmichael/latex-thesis
        docker tag mathematicalmichael/latex-thesis latex:thesis

    - name: Set up PATH for binaries
      run: echo "$(pwd)/bin" >> $GITHUB_PATH

    #- name: Generate figures with python
    #  run: make examples

    - name: Compile thesis with latexmk
      run: dmake

    - name: Clean up TeX build files
      run: dmake clean

    - name: Build presentation
      run: |
        cd presentation
        dmake
        dmake clean
